package bit.hibooks.setting;

public class ErrorMsgSet {
	public final static String HEADSETTING = "<link rel=\"stylesheet\" href=\"../assets/css/bootstrap.min.css\"><link rel=\"stylesheet\" href=\"../assets/css/animate.css\"><link rel=\"stylesheet\" href=\"../assets/css/owl.carousel.min.css\"><link rel=\"stylesheet\" href=\"../assets/css/chosen.min.css\"><link rel=\"stylesheet\" href=\"../assets/css/themify-icons.css\"><link rel=\"stylesheet\" href=\"../assets/css/fontawesome-all.css\"><link rel=\"stylesheet\" href=\"../assets/css/ionicons.min.css\"><link rel=\"stylesheet\" href=\"../assets/css/jquery-ui.css\"><link rel=\"stylesheet\" href=\"../assets/css/material-design-iconic-font.css\"><link rel=\"stylesheet\" href=\"../assets/css/meanmenu.min.css\"><link rel=\"stylesheet\" href=\"../assets/css/tippy.css\"><link rel=\"stylesheet\" href=\"../assets/css/bundle.css\"><link rel=\"stylesheet\" href=\"../assets/css/easyzoom.css\"><link rel=\"stylesheet\" href=\"../assets/css/style.css\"><link rel=\"stylesheet\" href=\"../assets/css/product-details.css\"><link rel=\"stylesheet\" href=\"../assets/css/responsive.css\"><link rel=\"stylesheet\" href=\"../assets/css/header.css\"><link rel=\"stylesheet\" href=\"http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css\" /><script src=\"../assets/js/vendor/modernizr-2.8.3.min.js\"></script>"; 
	public final static String DESIGN = "<script>const swalWithBootstrapButtons = Swal.mixin({customClass: {confirmButton: 'btn btn-primary', cancelButton: 'btn btn-default'}, buttonsStyling: false})</script>";
	public final static String BODYSETTING ="<script src=\"../assets/js/vendor/jquery-1.12.0.min.js\"></script><script src=\"http://code.jquery.com/ui/1.10.3/jquery-ui.js\" type=\"text/javascript\"></script><script src=\"../assets/js/popper.js\"></script><script src=\"../assets/js/bootstrap.min.js\"></script><script src=\"../assets/js/isotope.pkgd.min.js\"></script><script src=\"../assets/js/imagesloaded.pkgd.min.js\"></script><script src=\"../assets/js/jquery.counterup.min.js\"></script>\r\n" + 
			"<script src=\"../assets/js/waypoints.min.js\"></script><script src=\"../assets/js/ajax-mail.js\"></script><script src=\"../assets/js/owl.carousel.min.js\"></script><script src=\"../assets/js/plugins.js\"></script><script src=\"../assets/js/main.js\"></script><script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@9\"></script>";
}


